name: Update Version Badge

on:
  push:
    branches:
      - main
jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Extract version and update README
      run: |
        VERSION=$(python extract_version.py)
        echo "Current version: '$VERSION'"
        
        sed -i "s/badge\/version-[^-]*-[^-]*\.svg/badge\/version-$VERSION-blue.svg/" README.md

    - name: Commit and push if changed
      run: |
        git config --global user.email "slava.shilin07@mail.ru"
        git config --global user.name "Vyacheslav"
        git diff
        git commit -am "Update version badge"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.Commits_Token }}