name: Update Version Badge

on:
  push:
    branches:
      - main
jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Extract version and update README
      run: |
        VERSION=$(python .github/workflows/extract_version.py)
        echo "Got version from python: ${VERSION}"
        sed -i "s/badge\/version-[^-]*-[^-]*\.svg/badge\/version-$VERSION-green.svg/" README.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Commit and push if changed
      run: |
        echo "Committing changes..."
        git config --global user.email "slava.shilin07@mail.ru"
        git config --global user.name "Vyacheslav"
        git diff
        git commit -am "Update version badge"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.COMMITS_TOKEN }}